name: Primeira Pipeline

on:
    push:
    
jobs:
    teste:
        runs-on: ubuntu-latest

        steps:
            - name: Código
              uses: actions/checkout@v4

            - name: Teste
              run: echo "Pipeline funcionando"